settings:
  username: amriiiita07-ui
  commit_name: github-actions
  commit_email: github-actions@github.com
  commit_message: "📊 Update Recent Activity"
  max_lines: 5
  readme_file: ./README.md

activity:
  - type: CommitEvent
    text: "🔨 Pushed {commits} commit(s) to {repo}"
  - type: IssuesEvent
    text: "🐛 Opened issue #{number} in {repo}"
  - type: PullRequestEvent
    text: "🎉 Opened PR #{number} in {repo}"
  - type: ForkEvent
    text: "🍴 Forked {repo}"
  - type: WatchEvent
    text: "⭐ Starred {repo}"
  - type: CreateEvent
    text: "📂 Created {ref_type} in {repo}"
